"""Add foreign keys to rentals table

Revision ID: 426141544f6f
Revises: f60447c5162b
Create Date: 2018-02-16 14:33:46.552272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426141544f6f'
down_revision = 'f60447c5162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('rentals', sa.Column('lens_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rentals', 'lenses', ['lens_id'], ['id'])
    op.create_foreign_key(None, 'rentals', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_column('rentals', 'lens_id')
    op.drop_column('rentals', 'customer_id')
    # ### end Alembic commands ###
