"""Initial Migration

Revision ID: 5c817d1d39e5
Revises: 
Create Date: 2018-02-15 00:42:20.183879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c817d1d39e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('sign_up_fee', sa.Integer(), nullable=True),
    sa.Column('duration_in_months', sa.Integer(), nullable=True),
    sa.Column('discount_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('membership_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membership_type_id'], ['membership_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('number_in_stock', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenses_date_added'), 'lenses', ['date_added'], unique=False)
    op.create_index(op.f('ix_lenses_release_date'), 'lenses', ['release_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lenses_release_date'), table_name='lenses')
    op.drop_index(op.f('ix_lenses_date_added'), table_name='lenses')
    op.drop_table('lenses')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('membership_types')
    op.drop_table('genres')
    # ### end Alembic commands ###
