"""initdb

Revision ID: cd137e95fb30
Revises: 
Create Date: 2018-03-10 19:15:45.783691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd137e95fb30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focal_lengths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('sign_up_fee', sa.Integer(), nullable=True),
    sa.Column('duration_in_months', sa.Integer(), nullable=True),
    sa.Column('discount_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('membership_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membership_type_id'], ['membership_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('number_in_stock', sa.Integer(), nullable=True),
    sa.Column('number_available', sa.Integer(), nullable=True),
    sa.Column('mount_id', sa.Integer(), nullable=True),
    sa.Column('focal_length_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['focal_length_id'], ['focal_lengths.id'], ),
    sa.ForeignKeyConstraint(['mount_id'], ['mounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenses_date_added'), 'lenses', ['date_added'], unique=False)
    op.create_index(op.f('ix_lenses_release_date'), 'lenses', ['release_date'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_rented', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('lens_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lens_id'], ['lenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    op.drop_index(op.f('ix_lenses_release_date'), table_name='lenses')
    op.drop_index(op.f('ix_lenses_date_added'), table_name='lenses')
    op.drop_table('lenses')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('mounts')
    op.drop_table('membership_types')
    op.drop_table('focal_lengths')
    # ### end Alembic commands ###
