"""Add rentals table

Revision ID: f60447c5162b
Revises: 7e7a1df67763
Create Date: 2018-02-16 14:25:26.558425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60447c5162b'
down_revision = '7e7a1df67763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_rented', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
